### ISSUE TITLE
the example can not run

### ISSUE THREAD

**Issue by beanhacker** [os-js/osjs-example-vue-application#2]
lack of vue support in package.json.

**Comment by andersevenrud** [comment]
Could you elaborate a bit more on your problem ?

**Comment by beanhacker** [comment]
@andersevenrud no any vue rel info configed info in package.json, i've tried for one day, but can not install all it needed.
how do you use it usually as a vue template?

**Comment by andersevenrud** [comment]
Vue is included in package.json:

* https://github.com/os-js/osjs-example-vue-application/blob/master/package.json#L26
* https://github.com/os-js/osjs-example-vue-application/blob/master/package.json#L56

To use this as a template, place this project into your `src/packages` folder in the OS.js installation.

Then run `npm install` and `npm run build` *inside* the package folder.

Finally in your OS.js installation run `npm run package:discover` and it will be installed.

--

Alternatively, [create your own package](https://manual.os-js.org/tutorial/application/) from scratch and follow the [vue framework guide](https://manual.os-js.org/guide/framework/).

**Comment by andersevenrud** [comment]
If you have any issues with setting this up let me know.

This package works as intended, which is why I closed this issue.
